/*
 * HeadProcessorUnit (HPUCore) Register Definitions
 *
 * Copyright (c) 2016 Istituto Italiano di Tecnologia
 * Electronic Design Lab.
 *
 */

#define HPU_CTRL_REG                  0x00
#define HPU_LPBK_LR_CNFG_REG          0x04
#define HPU_RXDATA_REG                0x08
#define HPU_RXTIME_REG                0x0C
#define HPU_TXDATA_REG                0x10
#define HPU_DMA_REG                   0x14
#define HPU_STAT_RAW_REG              0x18
#define HPU_IRQ_REG                   0x1C
#define HPU_MSK_REG                   0x20
#define HPU_WRAPTIMESTAMP_REG         0x28
#define HPU_HSSAER_STAT_REG           0x34
#define HPU_HSSAER_RX_ERR_REG         0x38
#define HPU_HSSAER_RX_MSK_REG         0x3C
#define HPU_RX_CTRL_REG               0x40
#define HPU_TX_CTRL_REG	              0x44
#define HPU_RX_PAER_CNFG_REG          0x48
#define HPU_TX_PAER_CNFG_REG          0x4C
#define HPU_IP_CNFG_REG               0x50
#define HPU_FIFO_THRSH_REG            0x54
#define HPU_LPBK_AUX_CNFG_REG         0x58
#define HPU_ID_REG                    0x5C
#define HPU_AUX_RX_CTRL_REG           0x60
#define HPU_HSSAER_AUX_RX_ERR_REG     0x64
#define HPU_HSSAER_AUX_RX_MSK_REG     0x68
#define HPU_HSSAER_AUX_RX_ERR_THR_REG 0x6C
#define HPU_HSSAER_AUX_RX_ERR_CH0_REG 0x70
#define HPU_HSSAER_AUX_RX_ERR_CH1_REG 0x74
#define HPU_HSSAER_AUX_RX_ERR_CH2_REG 0x78
#define HPU_HSSAER_AUX_RX_ERR_CH3_REG 0x7C
#define HPU_SPNN_START_KEY_REG        0x80
#define HPU_SPNN_STOP_KEY_REG         0x84
#define HPU_SPNN_TX_MASK_REG          0x88
#define HPU_SPNN_RX_MASK_REG          0x8C
#define HPU_SPNN_CTRL_REG             0x90
#define HPU_SPNN_STATUS_REG           0x94
#define HPU_TLASTTO_REG               0xA0
#define HPU_TLASTCNT_REG              0xA4
#define HPU_TDATACNT_REG              0xA8
/*      Reserved                      0xAC */
#define HPU_GTRX_LEFT_REG             0xB0
#define HPU_GTRX_RIGHT_REG            0xB4
#define HPU_GTRX_AUX_REG              0xB8
#define HPU_GTTX_REG                  0xBC

#define HPU_CTRL_DMA_RUNNING            BIT(0)
#define HPU_CTRL_EN_DMA                 BIT(1)
#define HPU_CTRL_EN_INT                 BIT(2)
/* Reserved                             BIT(3) */
#define HPU_CTRL_FLUSH_RX_FIFO          BIT(4)
#define HPU_CTRL_LRXPAER_FIFO_FLUSH     BIT(5)
#define HPU_CTRL_RRXPAER_FIFO_FLUSH     BIT(6)
#define HPU_CTRL_AUXRXPAER_FIFO_FLUSH   BIT(7)
#define HPU_CTRL_FLUSH_TX_FIFO          BIT(8)
#define HPU_CTRL_AXISTREAM_LATENCY	    BIT(9)
/* Reserved                             BIT(10), BIT(11) */
#define HPU_CTRL_RESET_STREAM           BIT(12)
#define HPU_CTRL_ONLY_EVENTS_RX         BIT(13)
#define HPU_CTRL_ONLY_EVENTS_TX         BIT(14)
#define HPU_CTRL_FULL_TS                BIT(15)
/* Reserved                             BIT(16), BIT(17), BIT(18), BIT(19), BIT(20), BIT(21) */
#define HPU_CTRL_LOC_FAR_SPINN_LPBK_L   BIT(22)
#define HPU_CTRL_LOC_FAR_SPINN_LPBK_R   BIT(23)
#define HPU_CTRL_LOC_FAR_SPINN_LPBK_AUX (BIT(22) | BIT(23))
#define HPU_CTRL_REMOTE_LPBK            BIT(24)
#define HPU_CTRL_LOC_NEAR_LPBK          BIT(25)
#define HPU_CTRL_LOC_FAR_AUX_SAER_LPBK	BIT(26)
#define HPU_CTRL_LOC_FAR_AUX_PAER_LPBK	BIT(27)
#define HPU_CTRL_LOC_FAR_LSAER_LPBK     BIT(28)
#define HPU_CTRL_LOC_FAR_RSAER_LPBK     BIT(29)
#define HPU_CTRL_LOC_FAR_LPAER_LPBK     BIT(30)
#define HPU_CTRL_LOC_FAR_RPAER_LPBK     BIT(31)
#define HPU_CTRL_LPBK_MASK              GENMASK(31, 25) | GENMASK(23, 22)

#define HPU_RAWSTAT_RXDATAEMPTY		BIT(0)
#define HPU_RAWSTAT_RXDATAALMOSTEMPTY	BIT(1)
#define HPU_RAWSTAT_RXDATAFULL		BIT(2)
#define HPU_RAWSTAT_TXDATAEMPTY		BIT(3)
#define HPU_RAWSTAT_TXDATAALMOSTFULL	BIT(4)
#define HPU_RAWSTAT_TXDATAFULL		BIT(5)
#define HPU_RAWSTAT_TIMESTAMPWRAPPED	BIT(7)
#define HPU_RAWSTAT_RXBUFFERREADY	BIT(8)
#define HPU_RAWSTAT_RXFIFONOTEMPTY	BIT(9)
#define HPU_RAWSTAT_LRXPAERFIFOFULL	BIT(12)
#define HPU_RAWSTAT_RRXPAERFIFOFULL	BIT(13)
#define HPU_RAWSTAT_AUXRXPAERFIFOFULL	BIT(14)
#define HPU_RAWSTAT_RXFIFOTHRESHOLD	BIT(15)
#define HPU_RAWSTAT_GLBLRXERR_KO	BIT(16)
#define HPU_RAWSTAT_GLBLRXERR_TX	BIT(17)
#define HPU_RAWSTAT_GLBLRXERR_TO	BIT(18)
#define HPU_RAWSTAT_GLBLRXERR_OF	BIT(19)
#define HPU_RAWSTAT_TXSPINNDUMP 	BIT(20)
#define HPU_RAWSTAT_LSPINN_PARITY_ERR	BIT(21)
#define HPU_RAWSTAT_RSPINN_PARITY_ERR	BIT(22)
#define HPU_RAWSTAT_AUXSPINN_PARITY_ERR	BIT(23)
#define HPU_RAWSTAT_LSPINN_RXERR	BIT(24)
#define HPU_RAWSTAT_RSPINN_RXERR	BIT(25)
#define HPU_RAWSTAT_AUXSPINN_RXERR	BIT(26)

#define HPU_MSK_INT_RXFIFOFULL		BIT(2)
#define HPU_MSK_INT_TSTAMPWRAPPED	BIT(7)
#define HPU_MSK_INT_RXBUFFREADY		BIT(8)
#define HPU_MSK_INT_GLBLRXERR_KO	BIT(16)
#define HPU_MSK_INT_GLBLRXERR_RX	BIT(17)
#define HPU_MSK_INT_GLBLRXERR_TO	BIT(18)
#define HPU_MSK_INT_GLBLRXERR_OF	BIT(19)

#define HPU_RXCTRL_RXHSSAER_EN		BIT(0)
#define HPU_RXCTRL_RXPAER_EN		BIT(1)
#define HPU_RXCTRL_RXGTP_EN		    BIT(2)
#define HPU_RXCTRL_SPINN_EN		    BIT(3)
#define HPU_RXCTRL_RXHSSAERCH0_EN	BIT(8)
#define HPU_RXCTRL_RXHSSAERCH1_EN	BIT(9)
#define HPU_RXCTRL_RXHSSAERCH2_EN	BIT(10)
#define HPU_RXCTRL_RXHSSAERCH3_EN	BIT(11)

#define HPU_TXCTRL_TXHSSAER_EN		BIT(0)
#define HPU_TXCTRL_TXPAER_EN		BIT(1)
#define HPU_TXCTRL_SPINN_EN		    BIT(3)
#define HPU_TXCTRL_DEST_PAER		(0 << 4)
#define HPU_TXCTRL_DEST_HSSAER		(1 << 4)
#define HPU_TXCTRL_DEST_SPINN		(2 << 4)
#define HPU_TXCTRL_DEST_ALL		    (3 << 4)
#define HPU_TXCTRL_ROUTE		    BIT(6)
#define HPU_TXCTRL_TXHSSAERCH0_EN	BIT(8)
#define HPU_TXCTRL_TXHSSAERCH1_EN	BIT(9)
#define HPU_TXCTRL_TXHSSAERCH2_EN	BIT(10)
#define HPU_TXCTRL_TXHSSAERCH3_EN	BIT(11)
#define HPU_TXCTRL_IFACECFG_MASK        0xF7F
#define HPU_TXCTRL_TIMINGMODE_DELTA	(0 << 12)
#define HPU_TXCTRL_TIMINGMODE_ASAP	(1 << 12)
#define HPU_TXCTRL_TIMINGMODE_ABS	(2 << 12)
#define HPU_TXCTRL_TIMINGMODE_MASK	(3 << 12)
#define HPU_TXCTRL_REG_FORCE_RESYNC	BIT(14)
#define HPU_TXCTRL_REG_FORCE_REARM	BIT(15)
#define HPU_TXCTRL_REG_SYNCTIME_1mS	(0 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_5mS	(1 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_10mS	(2 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_50mS	(3 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_100mS	(4 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_500mS	(5 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_1000mS	(6 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_2500mS	(7 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_5000mS	(8 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_10S	(9 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_25S	(10 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_50S	(11 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_100S	(12 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_250S	(13 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_500S	(14 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_DISABLE	(15 << 16)
#define HPU_TXCTRL_REG_SYNCTIME_MASK	(15 << 16)
#define HPU_TXCTRL_REG_TS_20BIT		(0 << 20)
#define HPU_TXCTRL_REG_TS_24BIT		(1 << 20)
#define HPU_TXCTRL_REG_TS_28BIT		(2 << 20)
#define HPU_TXCTRL_REG_TS_32BIT		(3 << 20)
#define HPU_TXCTRL_REG_TS_MASK		(3 << 20)

#define HPU_IPCONFIG_RXSAER     BIT(0)
#define HPU_IPCONFIG_RXPAER     BIT(1)
#define HPU_IPCONFIG_RXGTP      BIT(2)
#define HPU_IPCONFIG_RXSPINN    BIT(3)
#define HPU_IPCONFIG_RXSAERCH   4
#define HPU_IPCONFIG_TXSAER     BIT(8)
#define HPU_IPCONFIG_TXPAER     BIT(9)
#define HPU_IPCONFIG_TXGTP      BIT(10)
#define HPU_IPCONFIG_TXSPINN    BIT(11)
#define HPU_IPCONFIG_TXSAERCH   12

#define HPU_SPINN_CTRL_REG_TO_DIS	BIT(0)
#define HPU_SPINN_CTRL_REG_START	BIT(1)
#define HPU_SPINN_CTRL_REG_STOP		BIT(2)
#define HPU_SPINN_CTRL_REG_AUX_KEYEN	BIT(8)
#define HPU_SPINN_CTRL_REG_R_KEYEN	BIT(16)
#define HPU_SPINN_CTRL_REG_L_KEYEN	BIT(24)
